CREATE SCHEMA IF NOT EXISTS apidb ;
USE apidb ;

CREATE TABLE IF NOT EXISTS apidb.Usuario(
  idUsuario INT NOT NULL AUTO_INCREMENT,
  nombre VARCHAR(336) NOT NULL,
  email VARCHAR(336) NOT NULL UNIQUE,
  estado TINYINT NOT NULL,
  PRIMARY KEY (idUsuario));